changelog:
  exclude:
    labels:
      - documentation
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: New Features and Improvements 🎉
      labels:
        - feature
        - enhancement
    - title: Bugfixes 🐛
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
