---
- name: Install Sysdig Agent
  block:
    - name: Install Dependencies
      include_tasks: agent/dependencies/{{ ansible_distribution | lower }}/install-{{ ansible_distribution | lower }}-dependencies.yml
      when: sysdig_agent_install_build_dependencies

    - name: Configure Sysdig Agent Repository
      ansible.builtin.yum_repository:
        baseurl: https://download.sysdig.com/stable/rpm/$basearch
        description: Sysdig Agent Repository
        gpgkey: https://download.sysdig.com/DRAIOS-GPG-KEY.public
        name: draios
      when: ansible_pkg_mgr in ["dnf", "yum"]

    - name: Install Sysdig Agent (rpm)
      ansible.builtin.package:
        name: "draios-agent{% if sysdig_agent_version is defined and sysdig_agent_version %}-{{ sysdig_agent_version }}{%endif%}"
        state: latest

    - name: Create dragent.yaml file
      template:
        src: dragent.yaml.j2
        dest: "/opt/draios/etc/dragent.yaml"
        owner: root
        group: root
        mode: 0644

    - name: Enable eBPF
      block:
        - name: (eBPF) Enable eBPF probe
          ansible.builtin.lineinfile:
            path: /etc/sysconfig/dragent
            regexp: SYSDIG_BPF_PROBE
            line: export SYSDIG_BPF_PROBE=
            create: true

        - name: (eBPF) Determine if sysdigcloud_probe module is loaded
          ansible.builtin.shell:
            cmd: lsmod
          register: lsmod_res

        - name: (eBPF) Stop dragent Service to unload kernel module
          ansible.builtin.service:
            name: dragent
            state: stopped
          when: lsmod_res.stdout | regex_search('sysdigcloud_probe')

        - name: (eBPF) Ensure kernel module is not loaded
          ansible.builtin.shell:
            cmd: rmmod sysdigcloud_probe
          when: lsmod_res.stdout | regex_search('sysdigcloud_probe')
      when: sysdig_agent_driver | lower == "ebpf"

    - name: (kmodule) Disable eBPF
      ansible.builtin.lineinfile:
        path: /etc/sysconfig/dragent
        regexp: SYSDIG_BPF_PROBE
        state: absent
      when: sysdig_agent_driver == "kmodule"

    - name: Start dragent Service
      block:
        - name: Start dragent Service
          service:
            name: dragent
            enabled: true
            state: started
      rescue:
        - name: Attempting to Start dragent Service with sysvinit
          sysvinit:
            name: dragent
            enabled: true
            state: started
  when: install_sysdig_agent
