---
- name: Install Kernel Headers (rpm)
  include_tasks: agent/dependencies/kernel-headers/redhat/install-rh-{{ kernel_type }}-headers.yml
  when:
    - ansible_kernel_version | regex_search(match_str)
    - ansible_facts.os_family == "RedHat"
  vars:
    - match_str: PAE
      kernel_type: pae
    - match_str: vzkernel
      kernel_type: vzkernel
    - match_str: uek
      kernel_type: uek
    - match_str: .*
      kernel_type: kernel-devel
