- name: (RHEL) Install Kernel Headers (7/8)
  ansible.builtin.command: yum -y install "kernel-devel-{{ ansible_kernel }}"
  args:
    creates: /usr/src/kernels/{{ ansible_kernel }}
  when: ansible_distribution_major_version in ["7", "8"]

- name: (RHEL) Install Kernel Headers (9)
  ansible.builtin.dnf:
    name: kernel-devel-matched
    state: present
  when: ansible_distribution_major_version in ["9"]

- name: (RHEL) Install epel and dkms
  when: agent_install_driver_type == "kmod"
  block:
    - name: (RHEL) Add epel GPG key
      ansible.builtin.rpm_key:
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}

    - name: (RHEL) Install epel
      ansible.builtin.command: yum -y install "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
      args:
        creates: /etc/yum.repos.d/epel.repo
      retries: 10
      delay: 3
      register: agent_install_epel_result
      until: agent_install_epel_result is not failed

    - name: (RHEL) Install dkms
      ansible.builtin.command: yum -y install dkms
      args:
        creates: /usr/sbin/dkms

- name: (RHEL) Install eBPF dependencies
  ansible.builtin.command: yum -y install clang elfutils-libelf-devel llvm
  args:
    creates: /usr/bin/clang
  when: agent_install_driver_type == "legacy_ebpf"
