# config.yaml
name: Molecule AMI updater

scms:
  github:
    kind: "github"
    spec:
      user: "updatecli"
      email: "updatecli@sysdig.com"
      owner: "sysdiglabs"
      repository: "agent-ansible-collection"
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      username: draios-jenkins
      branch: "main"

actions:
  ansible-molecule:
    kind: "github/pullrequest"
    scmid: "github"
    spec:
      automerge: true
      description: "Update the AMIs used by Molecule to the latest available"
      draft: false
      mergemethod: squash
      title: 'chore: update {{ requiredEnv "OS_TYPE" }} AMI IDs'

sources:
  {{- range (index .images (requiredEnv "OS_TYPE")) }}
  get-{{ .task_name }}:
    name: Get latest AMI for {{ .variant }}
    kind: aws/ami
    spec:
      region: {{ .region }}
      sortby: creationdateasc
      filters:
        - name: "name"
          values: {{ .image_name | quote }}
        - name: "architecture"
          values: {{ .architecture }}
        - name: "owner-id"
          values: {{ .owner_id | quote }}
  {{- end }}
targets:
  {{- range (index .images (requiredEnv "OS_TYPE")) }}
  {{- if .ebpfCapable }}
  update-{{ .task_name }}-ebpf:
    name: "Update AMI for {{ .variant }}"
    sourceid: "get-{{ .task_name }}"
    scmid: "github"
    kind: yaml
    spec:
      files:
        {{- range (index $.scenarios "ebpf") }}
        - {{ . }}
        {{- end}}
      key: "$.platforms[{{ .molecule_index }}].image"
  {{- end }}
  {{- end }}
  {{- range (index .images (requiredEnv "OS_TYPE")) }}
  update-{{ .task_name }}-kmodule:
    name: "Update AMI for {{ .variant }}"
    sourceid: "get-{{ .task_name }}"
    scmid: "github"
    kind: yaml
    spec:
      files:
        {{- range (index $.scenarios "kmodule") }}
        - {{ . }}
        {{- end}}
      key: "$.platforms[{{ .molecule_index }}].image"
  {{- end }}
