- name: Configure Sysdig Agent Repository
  ansible.builtin.yum_repository:
    baseurl: https://download.sysdig.com/stable/rpm/$basearch
    description: Sysdig Agent Repository
    gpgkey: https://download.sysdig.com/DRAIOS-GPG-KEY.public
    name: draios
  when: ansible_pkg_mgr in ["dnf", "yum"]

- name: Install Dependencies
  include_tasks: agent/dependencies/{{ ansible_distribution | lower }}/install-{{ ansible_distribution | lower }}-dependencies.yml
