---
- name: Install Sysdig Agent (rpm)
  ansible.builtin.package:
    name: "draios-agent{% if sysdig_agent_version is defined and sysdig_agent_version %}-{{ sysdig_agent_version }}{%endif%}"
    state: latest

- name: Start dragent Service
  block:
    - name: Start dragent Service
      service:
        name: dragent
        enabled: true
        state: started
  rescue:
    - name: Attempting to Start dragent Service with sysvinit
      sysvinit:
        name: dragent
        enabled: true
        state: started
