---
- name: (rpm) Configure Sysdig Agent Repository
  ansible.builtin.yum_repository:
    baseurl: "{{ agent_install_rpm_repository_url }}"
    description: Sysdig Agent Repository
    gpgkey: "{{ agent_install_rpm_repository_gpgkey }}"
    name: draios
