---
- name: (deb) Add Sysdig gpg Key
  ansible.builtin.get_url:
    url: "{{ agent_install_deb_repository_gpgkey }}"
    dest: /etc/apt/trusted.gpg.d/sysdig.asc
    mode: 0o644

- name: (deb) Remove a legacy Sysdig repository configurations
  ansible.builtin.apt_repository:
    repo: "deb https://download.sysdig.com/stable/deb stable-$(ARCH)/"
    filename: draios
    state: absent

- name: (deb) Configure Sysdig Repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/sysdig.asc] {{ agent_install_deb_repository_url }} stable-$(ARCH)/"
    filename: sysdig
    state: present
