---
dependency:
  name: galaxy
driver:
  name: ec2
lint: |
  set -e
  ansible-lint tasks/agent
  yamllint tasks/agent
platforms:
  - name: amzn2
    image_name: amzn2-ami-kernel-5.10*gp2
    image_filters:
      architecture: x86_64
    image_owner: "137112412989"  # Amazon
    instance_type: {{ instance_type }}
    region: {{ aws_region }}
    vpc_subnet_id: {{ vpc_subnet_id }}
  - name: al2023
    image_name: al2023-ami*
    image_filters:
      architecture: x86_64
    image_owner: "137112412989"  # Amazon
    instance_type: {{ instance_type }}
    region: {{ aws_region }}
    vpc_subnet_id: {{ vpc_subnet_id }}
  - name: centos7
    image_filters:
      architecture: x86_64
    image_name: "CentOS Linux 7*"
    image_owner: "125523088429"  # Red Hat CPE
    instance_type: {{ instance_type }}
    region: {{ aws_region }}
    vpc_subnet_id: {{ vpc_subnet_id }}
  - name: centos8
    boot_wait_seconds: 180
    image_filters:
      architecture: x86_64
    image_name: "CentOS Stream 8*"
    image_owner: "125523088429"  # Red Hat CPE
    instance_type: {{ instance_type }}
    vpc_subnet_id: {{ vpc_subnet_id }}
  - name: centos9
    image_filters:
      architecture: x86_64
    image_name: "CentOS Stream 9*"
    image_owner: "125523088429"  # Red Hat CPE
    instance_type: {{ instance_type }}
    region: {{ aws_region }}
    vpc_subnet_id: {{ vpc_subnet_id }}
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: agent
  create_sequence:
    - create
    - prepare
  converge_sequence:
    - create
    - prepare
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - create
    - prepare
    - converge
    - verify
    - destroy
verifier:
  name: ansible
