---
- name: Prepare
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Make sure python3 is installed
      package:
        name: python3
        state: present

    - name: Update Systems
      ansible.builtin.yum:
        name: "*"
        state: latest
      when: ansible_pkg_mgr in ['dnf', 'yum']

    - name: Update Systems
      ansible.builtin.apt:
        name: "*"
        update_cache: true
        state: latest
      when: ansible_pkg_mgr == "apt"

    - name: Reboot
      reboot:
        reboot_timeout: 3600
