---
- name: Set facts
  ansible.builtin.set_fact:
    agent_install_version: "{{ configuration | sysdig.agent.toAgentVersion }}"
    agent_install_driver_type: "{{ configuration | sysdig.agent.toAgentDriverType | lower }}"
    agent_install_probe_build_dependencies: "{{ configuration | sysdig.agent.toAgentInstallProbeBuildDependencies | bool }}"

- name: Install Sysdig Agent
  block:
    - name: Validate Environment
      ansible.builtin.include_tasks: agent/validations/platforms.yml

    - name: Install Dependencies
      ansible.builtin.include_tasks: agent/dependencies/{{ ansible_distribution | lower }}/install-{{ ansible_distribution | lower }}-dependencies.yml
      when: agent_install_probe_build_dependencies

    - name: Configure Sysdig Agent Repository
      ansible.builtin.include_tasks: "agent/configure-{{ 'rpm' if ansible_pkg_mgr in ['dnf', 'yum'] else 'deb' }}-repository.yml"

    - name: Install Sysdig Agent
      ansible.builtin.package:
        name: "draios-agent{% if ansible_pkg_mgr == 'apt' %}={% else %}-{% endif %}{{ agent_install_version }}"
        state: present

    - name: Create dragent.yaml file
      ansible.builtin.template:
        src: dragent.yaml.j2
        dest: "/opt/draios/etc/dragent.yaml"
        owner: root
        group: root
        mode: 0644

    - name: Enable eBPF
      when: agent_install_driver_type == "ebpf"
      block:
        - name: (eBPF) Enable eBPF probe
          ansible.builtin.lineinfile:
            path: /etc/sysconfig/dragent
            regexp: SYSDIG_BPF_PROBE
            line: export SYSDIG_BPF_PROBE=
            create: true
            mode: 0o644

        - name: (eBPF) Determine if sysdigcloud_probe module is loaded
          ansible.builtin.shell:
            cmd: |
              set -o pipefail
              lsmod | grep sysdigcloud_probe && echo -n LOADED || echo -n NOT_LOADED
            executable: bash
          register: agent_install_probe_loaded
          changed_when: agent_install_probe_loaded.stdout == 'LOADED'

        - name: (eBPF) Stop dragent Service to unload kernel module
          ansible.builtin.service:
            name: dragent
            state: stopped
          when: agent_install_probe_loaded.stdout == 'LOADED'

        - name: (eBPF) Ensure kernel module is not loaded
          ansible.builtin.command: modprobe -r sysdigcloud_probe
          register: agent_install_probe_removed
          when: agent_install_probe_loaded.stdout == 'LOADED'
          changed_when: agent_install_probe_removed.rc == 0

    - name: (kmodule) Disable eBPF
      ansible.builtin.lineinfile:
        path: /etc/sysconfig/dragent
        regexp: SYSDIG_BPF_PROBE
        state: absent
      when: agent_install_driver_type == "kmodule"

    - name: Start dragent Service
      block:
        - name: Start dragent Service
          ansible.builtin.service:
            name: dragent
            enabled: true
            state: started
      rescue:
        - name: Attempting to Start dragent Service with sysvinit
          ansible.builtin.sysvinit:
            name: dragent
            enabled: true
            state: started
