- name: (AlmaLinux) Install Kernel Headers (8)
  ansible.builtin.dnf:
    name: "kernel-devel-{{ ansible_kernel }}"
    state: present
  when: ansible_distribution_major_version == "8"

- name: (AlmaLinux) Install Kernel Headers (9)
  ansible.builtin.dnf:
    name: kernel-devel-matched
    state: present
  when: ansible_distribution_major_version == "9"

- name: (AlmaLinux) Install epel and dkms
  when: agent_install_driver_type == "kmod"
  block:
    - name: Add epel GPG key
      ansible.builtin.rpm_key:
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}

    - name: Install epel
      ansible.builtin.yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
        state: present
      retries: 10
      delay: 3
      register: result
      until: result is not failed

    - name: Install dkms
      ansible.builtin.yum:
        name: dkms
        state: present

- name: (AlmaLinux) Install Legacy eBPF dependencies
  ansible.builtin.yum:
    name: clang,elfutils-libelf-devel,llvm
    state: present
  when: agent_install_driver_type | lower == "legacy_ebpf"