---
- name: Install PAE Headers
  ansible.builtin.package:
    name: kernel-PAE-devel-{{ ansible_kernel }}
    state: present
  register: pae_kernel
  when: '"PAE" in ansible_kernel'

- name: Install OpenVZ Headers
  ansible.builtin.package:
    name: vzkernel-devel-{{ ansible_kernel }}
    state: present
  register: openvz_kernel
  when: '"stab" in ansible_kernel'

- name: Install UEK Headers
  ansible.builtin.package:
    name: kernel-uek-devel-{{ ansible_kernel }}
    state: present
  register: uek_kernel
  when: '"uek" in ansible_kernel'

- name: Install Kernel Headers
  include:
  ansible.builtin.package:
    name: kernel-devel-{{ ansible_kernel }}
    state: present
  when: pae_kernel is skipped and openvz_kernel is skipped and uek_kernel is skipped
