name: Lint and Test Role Changes

on:
  - pull_request

jobs:
  lint-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r molecule/requirements.txt

      - name: Run ansible-lint
        run: ansible-lint tasks/

  test-branch:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Expand templates for CI
        run: |
          find -path "*/molecule/*/molecule.yml.template" | xargs -L1 -- bash -c 'envsubst < $0 > ${0%.template}'
        shell: bash
        env:
          INSTANCE_TYPE: ${{ secrets.INSTANCE_TYPE }}
          REGION: ${{ secrets.REGION }}
          VPC_SUBNET_ID: ${{ secrets.VPC_SUBNET_ID }}
          SHOW_USAGE: false

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r molecule/requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.DRAIOS_GH_ACTIONS_ANSIBLE_MOLECULE_ROLE_ARN }}
          aws-region: us-east-1

      - name: Run Molecule tests
        run: |
          molecule test -s agent
