name: Lint and Test Collection Role Changes

on:
  - pull_request

jobs:
  lint-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@v6.16.0
        with:
          path: roles

  test-branch:
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - agent-smoke-ebpf
          - agent-smoke-kmodule
          - agent-uninstall-clean-all
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r molecule/requirements.txt
          ansible-galaxy collection install amazon.aws community.crypto

      - name: Expand templates for CI
        run: |
          find -path "*/molecule/*/*.yml.template" | xargs -L1 -- bash -c 'envsubst < $0 > ${0%.template}'
        shell: bash
        env:
          AGENT_ACCESS_KEY: ${{ secrets.AGENT_ACCESS_KEY }}
          COLLECTOR_URL: ${{ secrets.COLLECTOR_URL }}
          COLLECTOR_PORT: ${{ secrets.COLLECTOR_PORT }}
          INSTANCE_TYPE_AARCH: ${{ secrets.INSTANCE_TYPE_AARCH }}
          INSTANCE_TYPE_X86: ${{ secrets.INSTANCE_TYPE_X86 }}
          REGION: ${{ secrets.REGION }}
          VPC_SUBNET_ID: ${{ secrets.VPC_SUBNET_ID }}
          SHOW_USAGE: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.DRAIOS_GH_ACTIONS_ANSIBLE_MOLECULE_ROLE_ARN }}
          aws-region: ${{ secrets.REGION }}

      - name: Run Molecule tests
        run: |
          molecule test -s ${{ matrix.scenario }}
